name = "ai-chat-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
# AI_API_KEY = "your-api-key-here"
# AI_PROVIDER = "deepseek"  # or "openai", "custom"
# AI_MODEL = "deepseek-chat"  # or "gpt-4", etc.
# AI_BASE_URL = "https://api.deepseek.com/v1"  # for custom providers

[vars]
AI_PROVIDER = "deepseek"
AI_MODEL = "deepseek-chat"

# For production, use wrangler secret put to set sensitive values:
# wrangler secret put AI_API_KEY
